# Generated by Django 3.2.12 on 2022-05-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_expediente', '0001_initial'),
        ('modulo_control', '0002_auto_20220503_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
                ('descripcion_categoria', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ContieneValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id_examen_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_examen', models.CharField(max_length=8)),
                ('nombre_examen', models.CharField(max_length=40)),
                ('tipo_muestra', models.CharField(choices=[(1, 'sangre'), (2, 'orina'), (3, 'heces'), (4, 'tejidos')], max_length=15)),
                ('categoria', models.ManyToManyField(through='modulo_laboratorio.CategoriaExamen', to='modulo_laboratorio.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=40)),
                ('unidad_parametro', models.CharField(max_length=40, null=True)),
                ('examen_de_laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_laboratorio.examenlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioDeLaboratorioClinico',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('precio_servicio_clinica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examen_de_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.examenlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_resultado', models.DateField()),
                ('lic_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_control.liclaboratorioclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.paciente')),
                ('parametro', models.ManyToManyField(through='modulo_laboratorio.ContieneValor', to='modulo_laboratorio.Parametro')),
            ],
        ),
        migrations.CreateModel(
            name='EsperaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago_laboratorio', models.CharField(choices=[(1, 'Completo'), (2, 'Parcialmente'), (3, 'Pendiente')], default='-', max_length=15)),
                ('numero_cola_laboratorio', models.IntegerField()),
                ('consumo_laboratorio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.paciente')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.resultado')),
            ],
        ),
        migrations.AddField(
            model_name='contienevalor',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.parametro'),
        ),
        migrations.AddField(
            model_name='contienevalor',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.resultado'),
        ),
        migrations.AddField(
            model_name='categoriaexamen',
            name='examen_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.examenlaboratorio'),
        ),
    ]
