# Generated by Django 3.2.12 on 2022-05-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esperaexamen',
            name='fase_examenes_lab',
            field=models.CharField(choices=[('1', 'Preparado'), ('2', 'Finalizado')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tipo_muestra',
            field=models.CharField(choices=[('1', 'sangre'), ('2', 'orina'), ('3', 'heces'), ('4', 'tejidos')], max_length=15),
        ),
    ]
