# Generated by Django 3.2.12 on 2022-09-02 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0025_remove_recetaordenexamenlaboratorioitem_examen_de_laboratorio'),
        ('modulo_laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamenLaboratorio',
            fields=[
                ('id_orden_examen_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField(default=datetime.datetime.now)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenExamenLaboratorioItem',
            fields=[
                ('id_orden_examen_laboratorio_item', models.AutoField(primary_key=True, serialize=False)),
                ('orden_examen_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.ordenexamenlaboratorio')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.resultado')),
            ],
        ),
    ]
