# Generated by Django 3.2.12 on 2022-05-29 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0018_auto_20220528_1620'),
        ('modulo_laboratorio', '0002_auto_20220528_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esperaexamen',
            name='paciente',
        ),
        migrations.AddField(
            model_name='esperaexamen',
            name='expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.expediente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='examen_laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_laboratorio.examenlaboratorio'),
            preserve_default=False,
        ),
    ]
