# Generated by Django 3.2.12 on 2022-09-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0003_auto_20220909_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='orden_de_laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.esperaexamen'),
        ),
    ]
