# Generated by Django 3.2.12 on 2022-05-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0002_auto_20220528_2022'),
        ('modulo_laboratorio', '0003_auto_20220528_2017'),
    ]

    operations = [
    ]
