# Generated by Django 3.2.12 on 2022-09-11 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0004_resultado_orden_de_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
