# Generated by Django 3.2.12 on 2022-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0004_merge_0002_auto_20220528_2022_0003_auto_20220528_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperaexamen',
            name='fase_examenes_lab',
            field=models.CharField(choices=[('1', 'Preparado'), ('2', 'Finalizado')], default='1', max_length=20),
        ),
    ]
