# Generated by Django 3.2.12 on 2022-09-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0005_resultado_fecha_creacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('examen_laboratorio', 'orden_de_laboratorio')},
        ),
    ]
