# Generated by Django 3.2.12 on 2022-06-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0005_alter_esperaexamen_fase_examenes_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperaexamen',
            name='estado_pago_laboratorio',
            field=models.CharField(choices=[('1', 'Cancelado'), ('3', 'Pendiente')], default='3', max_length=15),
        ),
        migrations.AlterField(
            model_name='esperaexamen',
            name='fase_examenes_lab',
            field=models.CharField(choices=[('1', 'Recepción de muestra'), ('2', 'Resultados en Proceso'), ('3', 'Resultados Listos'), ('4', 'Resultados Entregado'), ('5', 'Proceso Finalizado')], default='1', max_length=25),
        ),
    ]
