# Generated by Django 3.2.12 on 2022-06-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0006_auto_20220601_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contienevalor',
            name='dato',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contienevalor',
            name='resultado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.resultado'),
        ),
    ]
