# Generated by Django 3.2.12 on 2022-10-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0006_alter_resultado_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperaexamen',
            name='fase_examenes_lab',
            field=models.CharField(choices=[('RC', 'Recepcion'), ('EP', 'En Proceso'), ('RL', 'Resultados Listos'), ('RE', 'Resultados Entregados'), ('PF', 'Proceso Finalizado')], default='RC', max_length=2),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fase_examenes_lab',
            field=models.CharField(choices=[('1', 'Recepción de muestra'), ('2', 'Resultados en Proceso'), ('3', 'Resultados Listos'), ('4', 'Resultados Entregados')], default='1', max_length=25),
        ),
    ]
