# Generated by Django 3.2.12 on 2022-06-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0007_auto_20220603_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contienevalor',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.resultado'),
        ),
        migrations.AlterUniqueTogether(
            name='contienevalor',
            unique_together={('resultado', 'parametro')},
        ),
    ]
