# Generated by Django 3.2.12 on 2023-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0007_auto_20221010_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='consumo_laboratorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
