# Generated by Django 3.2.12 on 2022-06-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0008_auto_20220603_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlaboratorio',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='resultado_por_defecto',
            field=models.CharField(blank=True, choices=[('NA', ''), ('P', 'POSITIVO'), ('N', 'NEGATIVO'), ('NAF', 'NEGATIVO A LA FECHA'), ('R', 'REACTIVO'), ('NR', 'NO REACTIVO'), ('NRAF', 'NO REACTIVO A LA FECHA')], default='NA', max_length=22),
        ),
        migrations.AddField(
            model_name='parametro',
            name='valor_por_defecto',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fecha_hora_elaboracion_de_reporte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fecha_hora_toma_de_muestra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tipo_muestra',
            field=models.CharField(blank=True, choices=[('NA', ''), ('1', 'sangre'), ('2', 'orina'), ('3', 'heces'), ('4', 'tejidos')], default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='examen_de_laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.examenlaboratorio'),
        ),
        migrations.CreateModel(
            name='RangoDeReferencia',
            fields=[
                ('id_rango_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=25)),
                ('valor_maximo', models.CharField(max_length=15, null=True)),
                ('valor_minimo', models.CharField(max_length=15, null=True)),
                ('unidad', models.CharField(blank=True, default='', max_length=8)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.parametro')),
            ],
        ),
    ]
