# Generated by Django 3.2.12 on 2023-05-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0008_resultado_consumo_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlaboratorio',
            name='precio_examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
