# Generated by Django 3.2.12 on 2022-06-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0009_auto_20220607_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre_categoria',
        ),
    ]
