# Generated by Django 3.2.12 on 2022-06-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0010_remove_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='codigo_examen',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='examen_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.examenlaboratorio'),
        ),
    ]
