# Generated by Django 3.2.12 on 2023-05-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0010_alter_examenlaboratorio_precio_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='orden_de_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.esperaexamen'),
        ),
    ]
