# Generated by Django 3.2.12 on 2022-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0011_auto_20220608_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='resultado_por_defecto',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='parametro',
            name='valor_por_defecto',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
