# Generated by Django 3.2.12 on 2023-05-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_laboratorio', '0011_alter_resultado_orden_de_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='lic_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
