# Generated by Django 3.2.12 on 2022-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0015_alter_examenlaboratorio_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangodereferencia',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
