# Generated by Django 3.2.12 on 2022-10-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciolaboratorioclinico',
            name='servicio_ptr',
        ),
        migrations.RemoveField(
            model_name='serviciomedico',
            name='servicio_ptr',
        ),
    ]
