# Generated by Django 3.2.12 on 2022-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0003_auto_20221010_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
