# Generated by Django 3.2.12 on 2022-10-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0004_imagen_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
    ]
