# Generated by Django 3.2.12 on 2022-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0005_remove_imagen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
