# Generated by Django 3.2.12 on 2022-10-10 13:56

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0006_alter_imagen_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='publicidad',
            new_name='publicacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='id_publicidad',
            new_name='id_publicacion',
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fecha_expedicion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl='public-read'), upload_to='publicaciones'),
        ),
    ]
