# Generated by Django 3.2.12 on 2022-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0007_auto_20221010_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='fecha_expiracion',
            new_name='validez_fecha_fin',
        ),
        migrations.RenameField(
            model_name='descuento',
            old_name='fecha_expedicion',
            new_name='validez_fecha_inicio',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_ultima_edicion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='codigo_descuento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
