# Generated by Django 3.2.12 on 2022-10-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0008_auto_20221011_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_vencimiento',
            new_name='validez_fecha_fin',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='validez_fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='validez_fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
