# Generated by Django 3.2.12 on 2022-10-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0009_auto_20221011_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
