# Generated by Django 3.2.12 on 2022-10-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0030_alter_tipoconsulta_nombre'),
        ('modulo_publicidad', '0011_auto_20221011_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomedico',
            name='tipo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.tipoconsulta'),
        ),
    ]
