# Generated by Django 3.2.12 on 2022-10-21 22:33

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0012_alter_serviciomedico_tipo_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='ImagenPublicacion',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl='public-read'), upload_to='servicios')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='modulo_publicidad.servicio')),
            ],
        ),
    ]
