# Generated by Django 3.2.12 on 2022-10-26 11:38

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_publicidad', '0013_auto_20221021_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpublicacion',
            name='archivo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl='public-read', location='static'), upload_to='publicaciones'),
        ),
        migrations.AlterField(
            model_name='imagenservicio',
            name='archivo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl='public-read', location='static'), upload_to='servicios'),
        ),
    ]
