# Generated by Django 3.2.12 on 2022-05-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='codigo_empleado',
            new_name='codigoEmpleado',
        ),
    ]
