# Generated by Django 3.2.12 on 2022-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_auto_20220415_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_activo',
            field=models.BooleanField(db_column='ES_ACTIVO', default=True),
        ),
    ]
