# Generated by Django 3.2.12 on 2022-05-03 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_clinica', models.CharField(max_length=40)),
                ('direccion_clinica', models.CharField(max_length=80)),
                ('telefono_clinica', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LaboratorioClinico',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(max_length=50)),
                ('codigo_laboratorio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LicLaboratorioClinico',
            fields=[
                ('id_lic_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('jvmp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=20)),
                ('descripcion_permiso', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_control.permiso')),
            ],
        ),
        migrations.AddField(
            model_name='permiso',
            name='empleado',
            field=models.ManyToManyField(through='modulo_control.PermisoEmpleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JefeRecursosHumanos',
            fields=[
                ('id_jefe_recursos_humanos', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JefeMarketing',
            fields=[
                ('id_jefe_marketing', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JefeFinanzas',
            fields=[
                ('id_jefe_finanzas', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id_enfermera', models.AutoField(primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('especialidad_doctor', models.CharField(max_length=40)),
                ('jvmp', models.IntegerField()),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
