# Generated by Django 3.2.12 on 2022-05-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_control', '0002_auto_20220503_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=15)),
                ('codigo_rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='roles',
            field=models.ManyToManyField(to='modulo_control.Rol'),
        ),
    ]
