# Generated by Django 3.2.12 on 2022-05-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_control', '0005_auto_20220514_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_control.rol'),
        ),
    ]
