# Generated by Django 3.2.12 on 2022-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_control', '0008_auto_20220514_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='codigo_rol',
            field=models.CharField(max_length=20),
        ),
    ]
