# Generated by Django 3.2.12 on 2022-08-02 04:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrindaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[(1, 'Matutino'), (2, 'Vespertino')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaMedica',
            fields=[
                ('id_constancia_medica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_emision', models.DateField(default=datetime.datetime.now)),
                ('dias_reposo', models.IntegerField()),
                ('diagnostico_constancia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('consulta_por', models.TextField(blank=True, max_length=200)),
                ('presente_enfermedad', models.TextField(blank=True, max_length=200)),
                ('examen_fisico', models.TextField(blank=True, max_length=200)),
                ('diagnostico', models.TextField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContieneConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cola', models.IntegerField()),
                ('fecha_de_cola', models.DateField(default=datetime.datetime.now)),
                ('consumo_medico', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado_cola_medica', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Parcialmente pagado'), ('3', 'Pagado')], default=1, max_length=20)),
                ('fase_cola_medica', models.CharField(choices=[('1', 'Agendado'), ('2', 'Anotado'), ('3', 'Preparado'), ('4', 'En espera'), ('5', 'En consulta'), ('6', 'Finalizado')], default=2, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ControlSubsecuente',
            fields=[
                ('id_control_subsecuente', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('id_dosis', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_dosis', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad_periodo_dosis', models.CharField(choices=[('h', 'Hora(s)'), ('d', 'Dia(s)'), ('s', 'Semana(s)'), ('m', 'Mes(es)')], default='d', max_length=6)),
                ('frecuencia_dosis', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad_frecuencia_dosis', models.CharField(choices=[('h', 'Hora(s)'), ('d', 'Dia(s)'), ('s', 'Semana(s)'), ('m', 'Mes(es)')], default='h', max_length=6)),
                ('cantidad_dosis', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad_de_medida_dosis', models.CharField(choices=[('got', 'gota'), ('mgota / µgota', 'microgota'), ('L', 'litro'), ('mL', 'mililitro'), ('µL', 'microlitro'), ('cc / cm³', 'centímetro cúbico'), ('fl oz', 'onza líquida'), ('cdita', 'cucharadita'), ('cda', 'cucharada'), ('Kg', 'kilogramo'), ('g', 'gramo'), ('mg', 'miligramo'), ('oz', 'onza'), ('disparos', 'disparos'), ('capsulas', 'cápsulas')], default='capsulas', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionConsulta',
            fields=[
                ('id_evolucion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion_expediente', models.DateField(default=datetime.datetime.now)),
                ('codigo_expediente', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_hospital', models.CharField(max_length=25)),
                ('nombre_hospital', models.CharField(max_length=50)),
                ('telefono_hospital', models.CharField(max_length=9)),
                ('codigo_pais', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('nombre_generico', models.CharField(max_length=25)),
                ('cantidad_medicamento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad_medicamento', models.CharField(choices=[('L', 'litro'), ('mL', 'mililitro'), ('µL', 'microlitro'), ('cc / cm³', 'centímetro cúbico'), ('fl oz', 'onza líquida'), ('Kg', 'kilogramo'), ('g', 'gramo'), ('mg', 'miligramo'), ('oz', 'onza'), ('capsulas', 'cápsulas')], max_length=8)),
                ('presentacion', models.CharField(choices=[('1', 'Frasco'), ('2', 'Ampolla'), ('3', 'Frasco vial'), ('4', 'Sobre'), ('5', 'Jeringa prellenada'), ('6', 'Bolsa'), ('7', 'Tubo'), ('8', 'Tarro'), ('9', 'Dispositivo precargado'), ('10', 'Pluma multidosis'), ('11', 'Cartucho'), ('12', 'Frasco gotero'), ('13', 'Capsulas'), ('14', 'Spray'), ('15', 'Suspensión')], default='13', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_paciente', models.CharField(max_length=40)),
                ('apellido_paciente', models.CharField(max_length=40)),
                ('fecha_nacimiento_paciente', models.DateField()),
                ('sexo_paciente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion_paciente', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('email_paciente', models.EmailField(default='', max_length=100)),
                ('responsable', models.CharField(blank=True, default='', max_length=40)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_temperatura', models.CharField(blank=True, choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], default=2, max_length=1)),
                ('unidad_peso', models.CharField(blank=True, choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default=1, max_length=3)),
                ('unidad_presion_arterial_diastolica', models.CharField(blank=True, default='mmHH', max_length=4, null=True)),
                ('unidad_presion_arterial_sistolica', models.CharField(blank=True, default='mmHH', max_length=4, null=True)),
                ('unidad_frecuencia_cardiaca', models.CharField(blank=True, default='PPM', max_length=3)),
                ('unidad_saturacion_oxigeno', models.CharField(blank=True, default='%', max_length=1)),
                ('valor_temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(15)])),
                ('valor_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)])),
                ('valor_presion_arterial_diastolica', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)])),
                ('valor_presion_arterial_sistolica', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(0)])),
                ('valor_frecuencia_cardiaca', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)])),
                ('valor_saturacion_oxigeno', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(0)])),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.consulta')),
                ('enfermera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaMedica',
            fields=[
                ('id_referencia_medica', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=30)),
                ('fecha_referencia', models.DateField(default=datetime.datetime.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id_receta_medica', models.AutoField(primary_key=True, serialize=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenExamenLaboratorio',
            fields=[
                ('id_orden_examen_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField(default=datetime.datetime.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta')),
            ],
        ),
    ]
