# Generated by Django 3.2.12 on 2022-05-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_laboratorio', '0001_initial'),
        ('modulo_expediente', '0001_initial'),
        ('modulo_control', '0002_auto_20220503_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamenlaboratorio',
            name='examen_de_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_laboratorio.examenlaboratorio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='contiene_consulta',
            field=models.ManyToManyField(through='modulo_expediente.ContieneConsulta', to='modulo_expediente.Consulta'),
        ),
        migrations.AddField(
            model_name='dosis',
            name='medicamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.medicamento'),
        ),
        migrations.AddField(
            model_name='dosis',
            name='receta_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.recetamedica'),
        ),
        migrations.AddField(
            model_name='contieneconsulta',
            name='consulta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
        ),
        migrations.AddField(
            model_name='contieneconsulta',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.expediente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examen_de_laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.ordenexamenlaboratorio'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='signos_vitales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.signosvitales'),
        ),
        migrations.AddField(
            model_name='brindaconsulta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
        ),
        migrations.AddField(
            model_name='brindaconsulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_control.doctor'),
        ),
    ]
