# Generated by Django 3.2.12 on 2022-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0003_referenciamedica_consulta_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(blank=True, choices=[('°F', 'Fahrenheit'), ('°C', 'Celsius')], default=2, max_length=2),
        ),
    ]
