# Generated by Django 3.2.12 on 2022-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0004_alter_signosvitales_unidad_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciamedica',
            name='acompanante',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
