# Generated by Django 3.2.12 on 2022-05-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0004_auto_20220506_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contieneconsulta',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
        ),
    ]
