# Generated by Django 3.2.12 on 2022-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0005_alter_contieneconsulta_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contieneconsulta',
            name='estado_cola_medica',
            field=models.CharField(choices=[('1', 'No pagado'), ('2', 'Parcialmente pagado'), ('3', 'Pagado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contieneconsulta',
            name='fase_cola_medica',
            field=models.CharField(choices=[('1', 'Agendado'), ('2', 'Agregar a cola'), ('3', 'Anotado'), ('4', 'Preparado'), ('5', 'En espera'), ('6', 'En consulta'), ('7', 'Atender paciente'), ('8', 'Ver expediente'), ('9', 'Finalizar consulta')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='contieneconsulta',
            unique_together={('expediente', 'fecha_de_cola')},
        ),
    ]
