# Generated by Django 3.2.12 on 2022-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0006_auto_20220506_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contieneconsulta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
