# Generated by Django 3.2.12 on 2022-08-11 10:00

from django.db import migrations, models
import django.utils.timezone
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0006_auto_20220810_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo_publico',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(default_acl='public-read'), upload_to='exams'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default='Lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(blank=True, choices=[('°F', 'Fahrenheit'), ('°C', 'Celsius')], default='°C', max_length=2),
        ),
    ]
