# Generated by Django 3.2.12 on 2022-08-11 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_expediente', '0007_auto_20220811_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('documento', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(default_acl=None), upload_to='exams')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.expediente')),
            ],
        ),
    ]
