# Generated by Django 3.2.12 on 2022-05-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0007_alter_contieneconsulta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.paciente'),
        ),
    ]
