# Generated by Django 3.2.12 on 2022-08-13 02:21

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0008_documentoexpediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo_publico',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl='public-read'), upload_to='exams'),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='documento',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl=None), upload_to='exams'),
        ),
    ]
