# Generated by Django 3.2.12 on 2022-05-08 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0008_alter_expediente_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='constancia_medica',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='modulo_expediente.constanciamedica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='examen_de_laboratorio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.ordenexamenlaboratorio'),
        ),
    ]
