# Generated by Django 3.2.12 on 2022-08-17 16:02

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0009_auto_20220813_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='plan_tratamiento',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='documento',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='code-geek-medic', default_acl=None, location='static'), upload_to='exams'),
        ),
    ]
