# Generated by Django 3.2.12 on 2022-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0010_auto_20220817_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dar_seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
