# Generated by Django 3.2.12 on 2022-05-10 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0010_auto_20220510_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contieneconsulta',
            name='consumo_medico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='contieneconsulta',
            name='estado_cola_medica',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Parcialmente pagado'), ('3', 'Pagado')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='contieneconsulta',
            name='fase_cola_medica',
            field=models.CharField(choices=[('1', 'Agendado'), ('2', 'Anotado'), ('3', 'Preparado'), ('4', 'En espera'), ('5', 'En consulta'), ('6', 'Finalizado')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_frecuencia_cardiaca',
            field=models.CharField(blank=True, default='PPM', max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_presion_arterial_diastolica',
            field=models.CharField(blank=True, default='mmHH', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_presion_arterial_sistolica',
            field=models.CharField(blank=True, default='mmHH', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(blank=True, choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_diastolica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_sistolica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_saturacion_oxigeno',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(15)]),
        ),
    ]
