# Generated by Django 3.2.12 on 2022-08-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0011_consulta_dar_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contieneconsulta',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
        ),
    ]
