# Generated by Django 3.2.12 on 2022-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0012_alter_contieneconsulta_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='antecedentes_personales',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefono',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contieneconsulta',
            unique_together=set(),
        ),
    ]
