# Generated by Django 3.2.12 on 2022-05-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0012_auto_20220512_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion_paciente',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_paciente',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
