# Generated by Django 3.2.12 on 2022-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0013_auto_20220512_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion_paciente',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
