# Generated by Django 3.2.12 on 2022-05-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_control', '0008_auto_20220514_2319'),
        ('modulo_expediente', '0014_alter_paciente_direccion_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='enfermera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_control.enfermera'),
        ),
    ]
