# Generated by Django 3.2.12 on 2022-08-18 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0015_horarioconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaconsulta',
            name='horario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.horarioconsulta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citaconsulta',
            name='fecha_cita',
            field=models.DateField(),
        ),
    ]
