# Generated by Django 3.2.12 on 2022-05-16 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0015_alter_signosvitales_enfermera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
