# Generated by Django 3.2.12 on 2022-08-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0016_auto_20220818_2219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citaconsulta',
            unique_together={('fecha_cita', 'horario')},
        ),
    ]
