# Generated by Django 3.2.12 on 2022-05-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0016_alter_signosvitales_valor_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='constancia_medica',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='examen_de_laboratorio',
        ),
        migrations.AddField(
            model_name='constanciamedica',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenexamenlaboratorio',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenciamedica',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta'),
            preserve_default=False,
        ),
    ]
