# Generated by Django 3.2.12 on 2022-08-19 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_expediente', '0017_alter_citaconsulta_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citaconsulta',
            unique_together={('fecha_cita', 'horario', 'empleado')},
        ),
    ]
