# Generated by Django 3.2.12 on 2022-05-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0017_auto_20220526_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sintoma',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
