# Generated by Django 3.2.12 on 2022-08-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0014_alter_contieneconsulta_unique_together'),
        ('modulo_expediente', '0018_alter_citaconsulta_unique_together'),
    ]

    operations = [
    ]
