# Generated by Django 3.2.12 on 2022-08-19 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0018_merge_20220819_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
