# Generated by Django 3.2.12 on 2022-06-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0019_medicamento_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosis',
            name='cantidad_dosis',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='frecuencia_dosis',
            field=models.IntegerField(default=8, max_length=2),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.medicamento'),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='periodo_dosis',
            field=models.IntegerField(default=7, max_length=2),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='unidad_de_medida_dosis',
            field=models.CharField(choices=[('got', 'gota'), ('mgota / µgota', 'microgota'), ('L', 'litro'), ('mL', 'mililitro'), ('µL', 'microlitro'), ('cc / cm³', 'centímetro cúbico'), ('fl oz', 'onza líquida'), ('cdita', 'cucharadita'), ('cda', 'cucharada'), ('Kg', 'kilogramo'), ('g', 'gramo'), ('mg', 'miligramo'), ('oz', 'onza'), ('disparos', 'disparos'), ('capsulas', 'cápsulas')], default='capsulas', max_length=17),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='unidad_frecuencia_dosis',
            field=models.CharField(choices=[('h', 'Hora(s)'), ('d', 'Dia(s)'), ('s', 'Semana(s)'), ('m', 'Mes(es)')], default='h', max_length=6),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='unidad_periodo_dosis',
            field=models.CharField(choices=[('h', 'Hora(s)'), ('d', 'Dia(s)'), ('s', 'Semana(s)'), ('m', 'Mes(es)')], default='d', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='presentacion',
            field=models.CharField(choices=[('1', 'Frasco'), ('2', 'Ampolla'), ('3', 'Frasco vial'), ('4', 'Sobre'), ('5', 'Jeringa prellenada'), ('6', 'Bolsa'), ('7', 'Tubo'), ('8', 'Tarro'), ('9', 'Dispositivo precargado'), ('10', 'Pluma multidosis'), ('11', 'Cartucho'), ('12', 'Frasco gotero'), ('13', 'Capsulas'), ('14', 'Spray'), ('15', 'Suspensión')], default='13', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='dosis',
            unique_together={('medicamento', 'receta_medica')},
        ),
    ]
