# Generated by Django 3.2.12 on 2022-06-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0020_auto_20220531_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosis',
            name='frecuencia_dosis',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='periodo_dosis',
            field=models.IntegerField(default=7),
        ),
    ]
