# Generated by Django 3.2.12 on 2022-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0020_citaconsulta_recordar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconsulta',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
