# Generated by Django 3.2.12 on 2022-09-02 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0001_initial'),
        ('modulo_expediente', '0021_alter_citaconsulta_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaOrdenExamenLaboratorio',
            fields=[
                ('id_receta_orden_examen_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField(default=datetime.datetime.now)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_expediente.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaOrdenExamenLaboratorioItem',
            fields=[
                ('id_receta_orden_examen_laboratorio_item', models.AutoField(primary_key=True, serialize=False)),
                ('examen_de_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_laboratorio.examenlaboratorio')),
                ('receta_orden_examen_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_expediente.recetaordenexamenlaboratorio')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdenExamenLaboratorio',
        ),
    ]