# Generated by Django 3.2.12 on 2022-06-02 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0021_auto_20220531_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosis',
            name='cantidad_dosis',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='frecuencia_dosis',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dosis',
            name='periodo_dosis',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
