# Generated by Django 3.2.12 on 2022-06-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0022_auto_20220601_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
