# Generated by Django 3.2.12 on 2022-08-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0022_alter_paciente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='codigo_expediente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
