# Generated by Django 3.2.12 on 2022-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0022_auto_20220902_1109'),
        ('modulo_expediente', '0023_alter_expediente_codigo_expediente'),
    ]

    operations = [
    ]
