# Generated by Django 3.2.12 on 2022-08-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0024_alter_signosvitales_enfermera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constanciamedica',
            name='diagnostico_constancia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
