# Generated by Django 3.2.12 on 2022-09-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0024_merge_20220902_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetaordenexamenlaboratorioitem',
            name='examen_de_laboratorio',
        ),
    ]
