# Generated by Django 3.2.12 on 2022-09-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0002_ordenexamenlaboratorio_ordenexamenlaboratorioitem'),
        ('modulo_expediente', '0026_recetaordenexamenlaboratorioitem_examen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetaordenexamenlaboratorioitem',
            unique_together={('receta_orden_examen_laboratorio', 'examen')},
        ),
    ]
