# Generated by Django 3.2.12 on 2022-09-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_laboratorio', '0002_ordenexamenlaboratorio_ordenexamenlaboratorioitem'),
        ('modulo_expediente', '0027_alter_recetaordenexamenlaboratorioitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaordenexamenlaboratorioitem',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_laboratorio.examenlaboratorio'),
        ),
    ]
