# Generated by Django 3.2.12 on 2022-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0029_tipoconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoconsulta',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
