# Generated by Django 3.2.12 on 2022-10-29 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0032_auto_20221029_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_frecuencia_cardiaca',
            field=models.CharField(default='PPM', max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_peso',
            field=models.CharField(choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default='Lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_presion_arterial_diastolica',
            field=models.CharField(default='mmHH', max_length=4),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_presion_arterial_sistolica',
            field=models.CharField(default='mmHH', max_length=4),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_saturacion_oxigeno',
            field=models.CharField(default='%', max_length=1),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(choices=[('°F', 'Fahrenheit'), ('°C', 'Celsius')], default='°C', max_length=2),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_frecuencia_cardiaca',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_peso',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_diastolica',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_sistolica',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_saturacion_oxigeno',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_temperatura',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(15)]),
            preserve_default=False,
        ),
    ]
