# Generated by Django 3.2.12 on 2022-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0034_auto_20221029_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='consulta_por',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(max_length=200),
        ),
    ]
