# Generated by Django 3.2.12 on 2022-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0035_auto_20221030_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion_paciente',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_paciente',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
