# Generated by Django 3.2.12 on 2022-11-25 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0036_auto_20221125_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default='Lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(blank=True, choices=[('°F', 'Fahrenheit'), ('°C', 'Celsius')], default='°C', max_length=2),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_frecuencia_cardiaca',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_diastolica',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_sistolica',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_saturacion_oxigeno',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(0)]),
        ),
    ]
