# Generated by Django 3.2.12 on 2022-11-25 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0037_auto_20221125_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_frecuencia_cardiaca',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_diastolica',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_presion_arterial_sistolica',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(350), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_saturacion_oxigeno',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(101), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='valor_temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
