# Generated by Django 3.2.12 on 2023-05-14 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0039_consulta_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contieneconsulta',
            name='hora_de_ingreso',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
