# Generated by Django 3.2.12 on 2023-05-14 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0040_contieneconsulta_hora_de_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora_de_ingreso',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
