# Generated by Django 3.2.12 on 2023-05-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0042_rename_hora_de_ingreso_consulta_hora_de_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('Lbs', 'Libras'), ('Kgs', 'Kilogramos')], default='Lbs', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='unidad_temperatura',
            field=models.CharField(blank=True, choices=[('°F', 'Fahrenheit'), ('°C', 'Celsius')], default='°C', max_length=2, null=True),
        ),
    ]
