# Generated by Django 3.2.12 on 2023-05-14 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0043_auto_20230514_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='hora_toma',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
