# Generated by Django 3.2.12 on 2023-05-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0045_consulta_hora_de_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='hora_de_entrada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hora_de_salida',
        ),
    ]
