# Generated by Django 3.2.12 on 2023-05-14 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_expediente', '0046_auto_20230514_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
